version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./back-end:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/saudacao
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=saudacao
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 